import numpy as np
from keras.src.utils import load_img, img_to_array
import os
from keras.src.saving import load_model

def preprocess_image(image_path, target_size=(256, 256)):
    img = load_img(image_path, target_size=target_size)
    x = img_to_array(img)
    x = np.expand_dims(x, axis=0)
    return x

def predict_image(image_data, model_path):
    # Load model
    model = load_model(model_path, compile=False)
    # Make prediction
    prediction = model.predict(image_data)
    # Get predicted class
    predicted_class = np.argmax(prediction)
    result = 0
    if predicted_class == 0:
        predicted_label = (
            f"is NOT generated by AI with {100*prediction[0][predicted_class]:.2f}% confidence"
        )
        result = 0
    else:
        predicted_label = (
            f"is generated by AI with {100*prediction[0][predicted_class]:.2f}% confidence"
        )
        result = 1
    print(predicted_label)
    return result

if __name__ == "__main__":
    images = os.listdir('E:/ki8/XLA/crawl_data/fake_face_image_tpdne_test')
    src_f = 'E:/ki8/XLA/crawl_data/fake_face_image_tpdne_test'
    model_path = 'mobilenet_new_50_12.h5'
    for img in images:
        print(img)
        processed_image = preprocess_image(f'{src_f}/{img}')
        result = predict_image(processed_image, model_path)
        if result==0:
            print("Ảnh real")
        else:
            print("Ảnh fake")
        print("--------------------------------------")

